name: qcfp_report
description: Quality Control Final Product Report Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  
  # UI Components
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  
  # Utilities
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  image_gallery_saver: ^2.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
